### ISSUE TITLE
Hyper error message: persistent connection closed

### ISSUE THREAD

**Issue by rkamudhan** [hyperhq/hypernetes#106] opened 2016-08-03 16:58 UTC
I previously worked on Hypernetes release v1.2.0 by downloading the library directly from the release package. I could create VMs and resolved the connectivity issues. Later, I started working in the source code release v1.2.0 and build the source code using `make quick-release` command. All other services are running without any issue, apart from kube-proxy. I am having the problem in using the pod-buildin-haproxy proxy, it always fails with the error message `"Can not get hyper version: An error occurred trying to connect: persistent connection closed"`, I want to use haproxy mode instead of iptables-mode. Whether it is related to any environment issue in source code build ?

I figured out the problem in getting the HTTP GET request from Hyper daemon in the hyper_client.go(at [#[L297](https://github.com/hyperhq/hypernetes/blob/master/pkg/kubelet/hyper/hyperclient.go#L297)](https://github.com/hyperhq/hypernetes/blob/master/pkg/kubelet/hyper/hyperclient.go#L311)), please let me know, someone came across the similar issue in their build.

**Comment by feiskyer** [comment] 2016-08-04 02:59
`kube-proxy` and `kubelet` shares same hyper client, if `kubelet` works, then `kube-proxy` should also work.

@rkamudhan could you increase log level of kube-proxy and post logs here?

**Comment by rkamudhan** [comment] 2016-08-04 09:10
@feiskyer I figured out that the `kubelet`shows running status for the command `systemctl status kubelet.service`, but in the following command

```
[root@silv-kh8nsbuild hypernetes]# /usr/bin/kubelet --logtostderr=false --log-dir=/var/log/kubernetes --v=4 --api-servers=http://<Kube Master IP>:8080 --address=0.0.0.0 --hostname-override=kh8nsbuild.domain.com --allow-privileged=false --container-runtime=hyper --network-provider=<Network provider IP>:4237 --max-pods=10 --maximum-dead-containers=0 --maximum-dead-containers-per-container=0 --minimum-container-ttl-duration=0

E0804 09:51:18.126406   27489 server.go:289] Failed running kubelet: failed to create kubelet: cannot get hyper version: An error occurred trying to connect: persistent connection closed
failed to create kubelet: cannot get hyper version: An error occurred trying to connect: persistent connection closed
```

I am getting the same log, `Can not get hyper version: An error occurred trying to connect: persistent connection closed`, for the kubelet also, so it is obvious that both the Kubelet and Kube-proxy are not running in both cases.

I have two setup, one setup is with hyper release package

```
[root@silv-kh8ns ~]# rpm -qa | grep hyper
hyperstart-0.6-1.fc23.x86_64
hyper-container-0.6-1.fc23.x86_64
xen-hypervisor-4.5.3-8.fc23.x86_64
```

And in the other setup, I build the hyperd and hyperctl library from the source code instruction as mentioned in the [README.md](https://github.com/hyperhq/hyperd/blob/master/README.md) for the release tag [v0.6.0](https://github.com/hyperhq/hyperd/releases/tag/v0.6.0)/commit [c6889d0](https://github.com/hyperhq/hyperd/commit/c6889d0ce574dc46107215df19f8868bff37ea38),

```
[root@silv-kh8nsbuild hyperd]# git log
commit c6889d0ce574dc46107215df19f8868bff37ea38
Merge: 0b67332 849df0f
Author: Xu Wang <gnawux@gmail.com>
Date:   Wed May 25 19:34:13 2016 +0800
Merge pull request #333 from gnawux/release_06
make 0.6.0 release
```

Whenever I run the hyperd from the release package, I am getting the following log,

[hyperd_release_package.txt](https://github.com/hyperhq/hypernetes/files/401169/hyperd_release_package.txt)

in line 62, you get the following logs

```
I0729 17:32:22.652344   27084 server.go:204] Registering GET, /version
I0729 17:32:22.652546   27084 server.go:204] Registering POST, /auth
I0729 17:32:22.652666   27084 server.go:204] Registering POST, /image/build
I0729 17:32:22.652823   27084 server.go:95] API listen on /var/run/hyper.sock
I0729 17:32:23.191368   27084 server.go:152] Calling GET /version
I0729 17:32:23.534221   27084 server.go:152] Calling GET /list
```

and for the source build, I am getting the following log file.
[hyperd_build_package.txt](https://github.com/hyperhq/hypernetes/files/401173/hyperd_build_package.txt)

in line 97, you get the following logs

```
I0803 22:51:25.104767   28149 server.go:204] Registering GET, /version
I0803 22:51:25.104835   28149 server.go:204] Registering POST, /auth
I0803 22:51:25.104882   28149 server.go:204] Registering POST, /image/build
I0803 22:51:25.104973   28149 server.go:95] API listen on /var/run/hyper.sock
I0803 22:51:25.106676   28149 hyperd.go:248] Hyper daemon: 0.6.0 0
I0803 22:51:34.089093   28149 server.go:152] Calling GET /v0.6.0/list
I0803 22:51:34.089189   28149 pod_routes.go:52] List type is pod, specified pod: [], specified vm: [], list auxiliary pod: false
I0803 22:51:58.029457   28149 server.go:152] Calling DELETE /v0.6.0/pod
E0803 22:51:58.029520   28149 server.go:170] Handler for DELETE /v0.6.0/pod returned error: Can not find that Pod(POD)
I0803 22:51:58.030278   28149 server.go:152] Calling DELETE /v0.6.0/pod
E0803 22:51:58.030320   28149 server.go:170] Handler for DELETE /v0.6.0/pod returned error: Can not find that Pod(Name)
I0803 22:51:58.031567   28149 server.go:152] Calling DELETE /v0.6.0/pod
E0803 22:51:58.031590   28149 server.go:170] Handler for DELETE /v0.6.0/pod returned error: Can not find that Pod(VM)
I0803 22:51:58.032215   28149 server.go:152] Calling DELETE /v0.6.0/pod
E0803 22:51:58.032236   28149 server.go:170] Handler for DELETE /v0.6.0/pod returned error: Can not find that Pod(name)
I0803 22:51:58.034484   28149 server.go:152] Calling DELETE /v0.6.0/pod
E0803 22:51:58.034506   28149 server.go:170] Handler for DELETE /v0.6.0/pod returned error: Can not find that Pod(Status)
I0803 22:52:08.830158   28149 server.go:152] Calling GET /v0.6.0/list
```

in the release package, I am getting the following call

```
I0729 17:32:23.191368   27084 server.go:152] Calling GET /version
I0729 17:32:23.534221   27084 server.go:152] Calling GET /list
```

but in the source code build, I am getting the following call, there is **no calling GET /version** from the server.go

```
I0803 22:51:25.106676   28149 hyperd.go:248] Hyper daemon: 0.6.0 0
I0803 22:51:34.089093   28149 server.go:152] Calling GET /v0.6.0/list
```

Hypernetes components expect the hyper daemon version, but the hyperd daemon is not responding with the version to the kubelet or for the kube-proxy in the source code build.

**Comment by feiskyer** [comment] 2016-08-09 03:00
@rkamudhan Could you have a try on master hyperd/runv?

**Comment by rkamudhan** [comment] 2016-08-10 16:11
The issue is the same. I am testing Hypernetes in fedora 23, with devstack-Openstack installation.

**Comment by feiskyer** [comment] 2016-08-12 08:59
@rkamudhan Sorry, I can't reproduce your problem. Could you try to call hyperd's `/version` api and check if hyperd is running properly?

**Comment by feiskyer** [comment] 2016-09-19 02:36
I'm closing this issue since it is not active for a month. Feel free to open it again if needed.

**Closed as completed by feiskyer** 2016-09-19 02:36 UTC
